FROM tb_utils AS build-env

WORKDIR /usr/src/app
COPY ./frontend/package.json ./
RUN npm install
COPY ./frontend/ .
RUN npm run build:prod

# Build runtime image
FROM nginx:latest
COPY --from=build-env /usr/src/app/dist/frontend /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
