FROM tb_service-utils AS build-env
ARG DEBUG

ENV DEBUG=$DEBUG

WORKDIR /usr/src/proxy/build
COPY ./proxy/build/package.json ./
RUN npm install
COPY ./proxy/build/ .
RUN npm start

# Build runtime image
FROM nginx:latest
COPY --from=build-env /usr/src/proxy/build/nginx.conf /etc/nginx/nginx.conf
